name: Bug report
description: File a bug report
labels: ["bug"]
body:
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: What did you expect to happen, and what happened instead?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: If possible, share a repo link + exact steps.
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste any console output or screenshots (redact tokens).

